joinfaces:
  primefaces:
    theme: saga

  faces:
    project-stage: Production

  server:
    shutdown: graceful

  spring:
    lifecycle:
      timeout-per-shutdown-phase: "30s"

#    autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    datasource:
#      driverClassName: org.postgresql.Driver
#      url: jdbc:postgresql://qcdb.postgres.database.azure.com/qcsystem
#      username:
#      password:
#
#      driver-class-name: org.postgresql.Driver

    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
